name: playermanager

services:
  db:
    image: postgres:latest
    container_name: pm_db
    restart: always
    volumes:
      - pm_db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      
volumes:
  pm_db_data:
