name: playermanager

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pm_app
    restart: always
    ports:
      - "3030:3030"
    environment:
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DATABASE_URL: "postgresql://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}"
    depends_on:
      - db

  db:
    image: postgres:latest
    container_name: pm_db
    restart: always
    volumes:
      - pm_db_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

volumes:
  pm_db_data:
